import { model } from "./firebase-config.js";

const AI_DETECTION_PROMPT = `You are an expert forensic analyst specializing in distinguishing AI-generated content from authentic content. Analyze this {mediaType} using the following structured reasoning process.

STEP 1 — WATERMARK AND BRANDING SCAN:
First, check for ANY visible watermarks, logos, or branding that indicate AI generation:
- "© Grok", "Grok", "Aurora" → generated by xAI's Grok
- "DALL·E", "DALL-E", "OpenAI", "ChatGPT" → generated by OpenAI
- "Midjourney" → generated by Midjourney
- "Adobe Firefly", "Generated by AI" → generated by Adobe
- "Made with AI", "AI Generated" → generic AI disclosure
- "Stable Diffusion", "Flux", "Ideogram", "Leonardo", "Runway" → other AI platforms
- Any SynthID or C2PA metadata indicators
CRITICAL: A copyright symbol (©) followed by an AI platform name is STRONG EVIDENCE of AI generation. Do NOT interpret it as a photographer or artist credit. AI generators add their own branded watermarks to output.

STEP 2 — OVERALL IMPRESSION AND COMPOSITION:
- Does the image look "too perfect"? Suspiciously ideal composition, lighting, or framing?
- Is there an uncanny "stock photo" quality with dramatic but uniform lighting?
- Does the scene feel plausible or does something feel subtly "off"?
- Is the subject matter a common AI generation theme (fantasy landscapes, perfect portraits, surreal scenes, dramatic mountain/cloud compositions)?

STEP 3 — DETAILED TECHNICAL EXAMINATION:
FOR IMAGES:
- Texture analysis: Zoom into skin, sky, foliage, rock, fabric. Real photos have random, irregular micro-textures. AI images show mathematically smooth or subtly repetitive patterns.
- Lighting consistency: Check if shadows, reflections, and light sources are physically consistent across the entire image.
- Anatomical accuracy: Examine hands, fingers, teeth, ears, jewelry, and accessories for subtle deformities.
- Text and signage: Check for garbled, inconsistent, or nonsensical text.
- Background coherence: Look for warped architecture, inconsistent perspective lines, or objects that blend unnaturally.
- Edge analysis: Examine boundaries between objects — AI often produces overly clean or subtly blurred edges.
- Noise profile: Real camera photos have characteristic sensor noise. AI images have different noise patterns or are unnaturally clean.
- Color transitions: Check for overly smooth gradients or unnatural color banding.

FOR VIDEOS:
- Frame-to-frame consistency: flickering, morphing, temporal artifacts
- Motion physics: unnatural movement of hair, clothing, water, smoke
- Lip-sync accuracy and facial movement naturalness
- Object permanence: things appearing/disappearing between frames
- Resolution and quality consistency across frames

STEP 4 — CONTEXTUAL AND SEMANTIC ANALYSIS:
- Could this exact scene realistically exist and be photographed with this level of perfection?
- Are there impossible or highly improbable elements that look superficially correct?
- Does the image contain elements common in AI art but rare in real photography?
- Consider the overall "feel" — AI images often have a dreamlike, hyper-real, or illustrated quality even when technically photorealistic.

You MUST respond in this exact JSON format and nothing else:
{
  "verdict": "AI_GENERATED" | "LIKELY_AI" | "UNCERTAIN" | "LIKELY_REAL" | "REAL",
  "confidence": <number between 0 and 100>,
  "summary": "<2-3 sentence summary explaining the key reasoning>",
  "indicators": [
    {
      "type": "ai" | "real",
      "detail": "<specific observation>"
    }
  ]
}

IMPORTANT GUIDELINES:
- If you find ANY AI platform watermark or branding, the verdict should be AI_GENERATED with high confidence.
- Modern AI generators (Grok, DALL-E 3, Midjourney v6+, Flux, Stable Diffusion 3) produce extremely photorealistic images. The ABSENCE of obvious artifacts does NOT mean an image is real.
- Weight watermark/branding evidence very heavily — it is the most reliable indicator.
- Be skeptical of perfection. Real photos usually have imperfections, noise, and slight compositional flaws.
- If genuinely uncertain, say so, but lean toward caution — it is better to flag a real image as UNCERTAIN than to miss an AI-generated one.`;

function fileToGenerativePart(file) {
  return new Promise((resolve) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      const base64Data = reader.result.split(",")[1];
      resolve({
        inlineData: {
          data: base64Data,
          mimeType: file.type,
        },
      });
    };
    reader.readAsDataURL(file);
  });
}

export async function analyzeContent(file) {
  const isVideo = file.type.startsWith("video/");
  const mediaType = isVideo ? "video" : "image";

  const prompt = AI_DETECTION_PROMPT.replace("{mediaType}", mediaType);
  const mediaPart = await fileToGenerativePart(file);

  const result = await model.generateContent([prompt, mediaPart]);
  const responseText = result.response.text();

  // Extract JSON from the response (handle markdown code blocks)
  const jsonMatch = responseText.match(/```(?:json)?\s*([\s\S]*?)```/);
  const jsonStr = jsonMatch ? jsonMatch[1].trim() : responseText.trim();

  try {
    return JSON.parse(jsonStr);
  } catch {
    // If JSON parsing fails, return a structured fallback
    return {
      verdict: "UNCERTAIN",
      confidence: 50,
      summary: responseText,
      indicators: [],
    };
  }
}
